### ISSUE TITLE
Making @Path("auth") configurable

### ISSUE THREAD

**Issue by pedroviniv** [cassiomolin/example-springboot-jersey-jwt#2]
I think it would be nice to make the `AuthenticationResource` `@Path` configurable through the `application.yaml` file. It would help another developers to use this library as a dependency of their projects without changing the code. the same thing could be done to refresh endpoint and so on.

**Comment by cassiomolin** [comment]
Annotation values must be compile-time constants. Some workarounds are possible, but there's no standard way to do it as of now.

This [issue](https://github.com/eclipse-ee4j/jaxrs-api/issues/65) tracks a request to add a dynamic way to register JAX-RS endpoints.
